export const DEFAULT_SMOKE_SUBREDDIT = 'nsfw';
export const DEFAULT_SMOKE_SUBREDDIT_PATH = `/r/${DEFAULT_SMOKE_SUBREDDIT}`;
export const DEFAULT_SMOKE_SORT_PATH = `${DEFAULT_SMOKE_SUBREDDIT_PATH}/top`;
export const DEFAULT_SMOKE_TIME_RANGE = 'month';
export const DEFAULT_SMOKE_ROUTE_PATH = `${DEFAULT_SMOKE_SORT_PATH}?t=${DEFAULT_SMOKE_TIME_RANGE}`;
export const DEFAULT_SMOKE_FIXTURE_PATHNAME = `${DEFAULT_SMOKE_SORT_PATH}/.json`;
export const DEFAULT_SMOKE_ABOUT_FIXTURE_PATHNAME = `${DEFAULT_SMOKE_SUBREDDIT_PATH}/about/.json`;
export const DEFAULT_SMOKE_FIXTURE_SOURCE_LIMIT = 10;
export const DEFAULT_SMOKE_FIXTURE_POST_COUNT = 5;
export const DEFAULT_SMOKE_FIXTURE_SOURCE_URL =
  `https://www.reddit.com${DEFAULT_SMOKE_FIXTURE_PATHNAME}?raw_json=1&t=${DEFAULT_SMOKE_TIME_RANGE}&limit=${DEFAULT_SMOKE_FIXTURE_SOURCE_LIMIT}`;
export const DEFAULT_SMOKE_ABOUT_SOURCE_URL =
  `https://www.reddit.com${DEFAULT_SMOKE_ABOUT_FIXTURE_PATHNAME}?raw_json=1`;
